version: '3.6'

services:

  master-diet-frontend:
    container_name: master-diet-frontend
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true